from src.services import ServiceStatus

# Website links with icons (icon mapping centralized here, not in template)
websites = [
    {
        "name": "task-manager",
        "url": "https://task-manager.mnalavadi.org",
        "description": "Task Manager",
        "icon": "📝",
    },
    {
        "name": "energyMonitor",
        "url": "https://energy-monitor.mnalavadi.org",
        "description": "Energy Monitor",
        "icon": "⚡️",
    },
    {
        "name": "USC-vis",
        "url": "https://usc-vis.mnalavadi.org",
        "description": "USC checkin visualizer",
        "icon": "💪🏾",
    },
    {
        "name": "trainspotter",
        "url": "https://trainspotter.mnalavadi.org",
        "description": "Spot when the next train comes!",
        "icon": "🚃",
    },
    {
        "name": "inspectordetector",
        "url": "https://inspectordetector.mnalavadi.org",
        "description": "Gute Schwarzfahrt!",
        "icon": "🚨",
    },
    {
        "name": "iOS Health Dump",
        "url": "https://ios-health-dump.mnalavadi.org",
        "description": "Data from iOS Health app",
        "icon": "⚕️",
    },
    {
        "name": "pingpong",
        "url": "https://pingpong.mnalavadi.org",
        "description": "Shared Expense Tracker",
        "icon": "🏓",
    },
    {"name": "Trace", "url": "https://trace.mnalavadi.org", "description": "GPS Tracker", "icon": "📍"},
]
websites.sort(key=lambda x: x["name"].lower())


canned_service_statuses = [
    ServiceStatus(
        name="projects_atc_tour_extension.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="27.768s",
        last_error=None,
        full_status="",
        project_group="atc_tour_extension",
    ),
    ServiceStatus(
        name="projects_energy_monitor.service",
        is_active=True,
        is_failed=False,
        uptime="24h",
        memory=None,
        cpu="1h 31min 6.328s",
        last_error="Command '['git', 'add', 'data/energy.db.bk']' returned non-zero exit status 128.",
        full_status="",
        project_group="energy_monitor",
    ),
    ServiceStatus(
        name="projects_flight_calendar_updater.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="32.059s",
        last_error=None,
        full_status="",
        project_group="flight_calendar_updater",
    ),
    ServiceStatus(
        name="projects_incognita-dashboard.service",
        is_active=True,
        is_failed=False,
        uptime="1 day 19h",
        memory=None,
        cpu="1h 53min 15.331s",
        last_error=None,
        full_status="",
        project_group="incognita",
    ),
    ServiceStatus(
        name="projects_incognita-data-api.service",
        is_active=True,
        is_failed=False,
        uptime="1 day 19h",
        memory=None,
        cpu="1min 43.418s",
        last_error=None,
        full_status="",
        project_group="incognita",
    ),
    ServiceStatus(
        name="projects_incognita-data-backup-scheduler.service",
        is_active=True,
        is_failed=False,
        uptime="1 day 19h",
        memory=None,
        cpu="27.103s",
        last_error=None,
        full_status="",
        project_group="incognita",
    ),
    ServiceStatus(
        name="projects_ios-health-dump-data-backup-scheduler.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="7.238s",
        last_error=None,
        full_status="",
        project_group="ios-health-dump",
    ),
    ServiceStatus(
        name="projects_ios-health-dump.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="27min 41.411s",
        last_error=None,
        full_status="",
        project_group="ios-health-dump",
    ),
    ServiceStatus(
        name="projects_pingpong.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="37min 33.152s",
        last_error=None,
        full_status="",
        project_group="pingpong",
    ),
    ServiceStatus(
        name="projects_servicemonitor.service",
        is_active=True,
        is_failed=False,
        uptime="16h",
        memory=None,
        cpu="9min 37.485s",
        last_error=None,
        full_status="",
        project_group="servicemonitor",
    ),
    ServiceStatus(
        name="projects_task-manager-data-backup-scheduler.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="1.683s",
        last_error=None,
        full_status="",
        project_group="task-manager",
    ),
    ServiceStatus(
        name="projects_task-manager.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="30min 41.554s",
        last_error=None,
        full_status="",
        project_group="task-manager",
    ),
    ServiceStatus(
        name="projects_train_tracker.service",
        is_active=True,
        is_failed=False,
        uptime="24h",
        memory=None,
        cpu="2h 35min 56.973s",
        last_error=None,
        full_status="",
        project_group="train_tracker",
    ),
    ServiceStatus(
        name="projects_train_tracker_site.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="2h 8min 30.003s",
        last_error=None,
        full_status="",
        project_group="train_tracker",
    ),
    ServiceStatus(
        name="projects_trainspotter.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="47min 44.972s",
        last_error=None,
        full_status="",
        project_group="trainspotter",
    ),
    ServiceStatus(
        name="projects_usc-vis-data-backup-scheduler.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="1.042s",
        last_error=None,
        full_status="",
        project_group="usc-vis",
    ),
    ServiceStatus(
        name="projects_usc-vis.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="37min 21.890s",
        last_error=None,
        full_status="",
        project_group="usc-vis",
    ),
    ServiceStatus(
        name="projects_wordle_alarm.service",
        is_active=True,
        is_failed=False,
        uptime="2 days",
        memory=None,
        cpu="3min 14.560s",
        last_error=None,
        full_status="",
        project_group="wordle_alarm",
    ),
]
